# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0e9c48d75b7674fc59636dc1b747c21647aac0a5483d672fe37d4955d927527a90b86a945a1180a7a0c4c2c6ce5548b2360b4ef54a15249c5b78b9cae5e984d

test:
  secret_key_base: 69f16a3985ff702657d7a6d8948cf00c1ba90de234c349dec60af7730abfbf0d68b389cab077b6ac7a7cf5eb3a55ecf8ea61d1ddfa035bc6bcfd9c884e240e68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
